INFO 2023-09-09 11:16:39,738 autoreload 5584 14940 Watching for file changes with StatReloader
INFO 2023-09-09 11:16:47,048 basehttp 5584 14028 "GET / HTTP/1.1" 200 23
WARNING 2023-09-09 11:16:49,213 log 5584 14028 Not Found: /favicon.ico
WARNING 2023-09-09 11:16:49,213 basehttp 5584 14028 "GET /favicon.ico HTTP/1.1" 404 2442
INFO 2023-09-09 11:54:43,542 autoreload 6680 5508 Watching for file changes with StatReloader
INFO 2023-09-09 11:59:10,254 autoreload 6680 5508 D:\св╗аю\Django_Framework\my_project\hw3_app\views.py changed, reloading.
INFO 2023-09-09 11:59:10,996 autoreload 11488 12732 Watching for file changes with StatReloader
ERROR 2023-09-09 11:59:17,948 log 11488 3240 Internal Server Error: /
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: mainapp\index.html
ERROR 2023-09-09 11:59:17,952 basehttp 11488 3240 "GET / HTTP/1.1" 500 82370
INFO 2023-09-09 12:01:07,358 autoreload 532 12508 Watching for file changes with StatReloader
ERROR 2023-09-09 12:01:11,357 log 532 11500 Internal Server Error: /
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: mainapp\index.html
ERROR 2023-09-09 12:01:11,361 basehttp 532 11500 "GET / HTTP/1.1" 500 82370
INFO 2023-09-09 12:04:08,165 autoreload 2152 7456 Watching for file changes with StatReloader
ERROR 2023-09-09 12:04:11,133 log 2152 6152 Internal Server Error: /
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: mainapp\index.html
ERROR 2023-09-09 12:04:11,139 basehttp 2152 6152 "GET / HTTP/1.1" 500 82370
WARNING 2023-09-09 12:05:14,177 log 2152 6152 Not Found: /mainapp/index.html
WARNING 2023-09-09 12:05:14,177 basehttp 2152 6152 "GET /mainapp/index.html HTTP/1.1" 404 2969
ERROR 2023-09-09 12:05:39,125 log 2152 6152 Internal Server Error: /index
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: mainapp\index.html
ERROR 2023-09-09 12:05:39,129 basehttp 2152 6152 "GET /index HTTP/1.1" 500 82415
INFO 2023-09-09 12:06:22,081 autoreload 2152 7456 D:\св╗аю\Django_Framework\my_project\hw3_app\views.py changed, reloading.
INFO 2023-09-09 12:06:23,057 autoreload 5440 12720 Watching for file changes with StatReloader
ERROR 2023-09-09 12:06:24,752 log 5440 14524 Internal Server Error: /index
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app\index.html
ERROR 2023-09-09 12:06:24,756 basehttp 5440 14524 "GET /index HTTP/1.1" 500 82552
ERROR 2023-09-09 12:06:26,420 log 5440 14524 Internal Server Error: /index
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app\index.html
ERROR 2023-09-09 12:06:26,423 basehttp 5440 14524 "GET /index HTTP/1.1" 500 82552
INFO 2023-09-09 12:08:10,920 autoreload 5440 12720 D:\св╗аю\Django_Framework\my_project\hw3_app\views.py changed, reloading.
INFO 2023-09-09 12:08:11,669 autoreload 14436 6524 Watching for file changes with StatReloader
ERROR 2023-09-09 12:08:15,013 log 14436 9072 Internal Server Error: /
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app\index.html
ERROR 2023-09-09 12:08:15,018 basehttp 14436 9072 "GET / HTTP/1.1" 500 82370
INFO 2023-09-09 12:12:13,788 autoreload 14436 6524 D:\св╗аю\Django_Framework\my_project\hw3_app\views.py changed, reloading.
INFO 2023-09-09 12:12:14,709 autoreload 8876 4816 Watching for file changes with StatReloader
ERROR 2023-09-09 12:13:03,443 log 8876 13512 Internal Server Error: /
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app\index.html
ERROR 2023-09-09 12:13:03,448 basehttp 8876 13512 "GET / HTTP/1.1" 500 82370
INFO 2023-09-09 12:13:04,174 autoreload 8876 4816 D:\св╗аю\Django_Framework\my_project\hw3_app\views.py changed, reloading.
INFO 2023-09-09 12:13:04,919 autoreload 4612 9516 Watching for file changes with StatReloader
ERROR 2023-09-09 12:13:19,587 log 4612 15572 Internal Server Error: /index
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app\index.html
ERROR 2023-09-09 12:13:19,590 basehttp 4612 15572 "GET /index HTTP/1.1" 500 82415
INFO 2023-09-09 12:15:55,062 autoreload 8312 1996 Watching for file changes with StatReloader
ERROR 2023-09-09 12:15:57,484 log 8312 392 Internal Server Error: /
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app\index.html
ERROR 2023-09-09 12:15:57,490 basehttp 8312 392 "GET / HTTP/1.1" 500 82370
INFO 2023-09-09 12:17:10,225 autoreload 8312 1996 D:\св╗аю\Django_Framework\my_project\hw3_app\views.py changed, reloading.
INFO 2023-09-09 12:17:10,982 autoreload 1888 6296 Watching for file changes with StatReloader
INFO 2023-09-09 12:17:13,412 basehttp 1888 10752 "GET / HTTP/1.1" 200 641
WARNING 2023-09-09 12:17:13,752 basehttp 1888 10752 "GET /static/css/slyle_main.css HTTP/1.1" 404 1813
INFO 2023-09-09 12:17:19,552 basehttp 1888 11372 "GET /orders HTTP/1.1" 301 0
ERROR 2023-09-09 12:17:20,057 log 1888 1232 Internal Server Error: /orders/
Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: hw3_app_order

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\св╗аю\Django_Framework\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: hw3_app_order
ERROR 2023-09-09 12:17:20,095 basehttp 1888 1232 "GET /orders/ HTTP/1.1" 500 203452
INFO 2023-09-09 12:18:07,758 basehttp 1888 1232 "GET /index HTTP/1.1" 200 641
WARNING 2023-09-09 12:18:07,783 basehttp 1888 1232 "GET /static/css/slyle_main.css HTTP/1.1" 404 1813
INFO 2023-09-09 12:18:09,853 basehttp 1888 9368 "GET /contact HTTP/1.1" 301 0
INFO 2023-09-09 12:18:09,859 basehttp 1888 8400 "GET /contact/ HTTP/1.1" 200 651
WARNING 2023-09-09 12:18:09,890 basehttp 1888 8400 "GET /static/css/slyle_main.css HTTP/1.1" 404 1813
INFO 2023-09-09 12:18:11,236 basehttp 1888 7584 "GET /about HTTP/1.1" 301 0
INFO 2023-09-09 12:18:11,247 basehttp 1888 12992 "GET /about/ HTTP/1.1" 200 669
WARNING 2023-09-09 12:18:11,277 basehttp 1888 12992 "GET /static/css/slyle_main.css HTTP/1.1" 404 1813
INFO 2023-09-09 12:18:14,204 basehttp 1888 6696 "GET /index HTTP/1.1" 200 641
WARNING 2023-09-09 12:18:14,237 basehttp 1888 6696 "GET /static/css/slyle_main.css HTTP/1.1" 404 1813
INFO 2023-09-09 12:18:15,684 basehttp 1888 12084 "GET /about/ HTTP/1.1" 200 669
WARNING 2023-09-09 12:18:15,711 basehttp 1888 12084 "GET /static/css/slyle_main.css HTTP/1.1" 404 1813
